"""
Configuration file for the Sphinx documentation builder.

This file only contains a selection of the most common options. For a full
list see the documentation:
https://www.sphinx-doc.org/en/master/usage/configuration.html
"""

import datetime
import os
from urllib.parse import urljoin

from packaging.version import Version

import pds

# -- Project information -----------------------------------------------------
# The documented project's name
project = "pds"

# A copyright statement in the style '2008, Author Name'.
copyright = f"2020-{datetime.datetime.now(tz=datetime.UTC).year}, ITER Organization"
# The author name(s) of the document
author = "ITER Organization"

# Parse urls here for convenience, to be re-used

# ITER GitHub organization
iter_github = "https://github.com/iterorganization/"

# PDS
repository_url = urljoin(iter_github, "IMAS-PDS/")

# Which ref :src: links point at. Read the branch/tag from the build environment so
# that docs built from a branch link to that branch's code, rather than always
# resolving against master and showing a reader code that has since moved.
git_ref = (
    os.environ.get("READTHEDOCS_GIT_IDENTIFIER")
    or os.environ.get("GITHUB_REF_NAME")
    or "master"
)
blob_url = urljoin(repository_url, f"blob/{git_ref}/")


# Configuration of sphinx.ext.extlinks
# See https://www.sphinx-doc.org/en/master/usage/extensions/extlinks.html
# unique name: (base URL, label prefix)
extlinks = {
    "src": (blob_url + "%s", "IMAS-PDS/%s"),
}

full_version = Version(pds.__version__)

# version: The major project version, used as the replacement for |version|.
#   For example, for the Python documentation, this may be something like 2.6.
version = full_version.base_version

# release: The full project version, used as the replacement for |release| and
#   e.g. in the HTML templates. For example, for the Python documentation, this
#   may be something like 2.6.0rc1
release = str(full_version)


# -- General configuration ---------------------------------------------------
# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",  # To auto-generate docs from Python docstrings
    "sphinx.ext.napoleon",  # Support for NumPy and Google style docstrings
    "sphinx.ext.intersphinx",  # Generate links to other documentation files
    "sphinx.ext.extlinks",  # For shortening internal links
    "myst_parser",  # Lets .md files (the workflow READMEs) be included directly
    "sphinx_immaterial",  # Sphinx immaterial theme
]

# The master toctree document.
master_doc = "index"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
# "generated" catches leftover autosummary output from before the API section was
# removed: it is untracked, so a working tree can still have it, and an orphan page
# fails the build under -W even though a clean CI checkout passes.
exclude_patterns = ["_build", "generated", "Thumbs.db", ".DS_Store"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
# today = ''
# Else, today_fmt is used as the format for a strftime call.
today_fmt = "%Y-%m-%d"


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = "sphinx_immaterial"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output
# and
# https://sphinx-immaterial.readthedocs.io/en/latest/customization.html#confval-html_theme_options
html_theme_options = {
    "repo_url": "https://github.com/iterorganization/IMAS-PDS",
    "repo_name": "IMAS-PDS",
    "icon": {
        "repo": "fontawesome/brands/github",
    },
    "features": [
        # "navigation.expand",
        # "navigation.tabs",
        "navigation.sections",
        "navigation.instant",
        # "header.autohide",
        "navigation.top",
        # "navigation.tracking",
        # "search.highlight",
        # "search.share",
        # "toc.integrate",
        "toc.follow",
        "toc.sticky",
        # "content.tabs.link",
        "announce.dismiss",
    ],
    # "toc_title_is_page_title": True,
    # "globaltoc_collapse": True,
    "palette": [
        {
            "media": "(prefers-color-scheme: light)",
            "scheme": "default",
            "primary": "indigo",
            "accent": "green",
            "toggle": {
                "icon": "material/lightbulb-outline",
                "name": "Switch to dark mode",
            },
        },
        {
            "media": "(prefers-color-scheme: dark)",
            "scheme": "slate",
            "primary": "light-blue",
            "accent": "lime",
            "toggle": {
                "icon": "material/lightbulb",
                "name": "Switch to light mode",
            },
        },
    ],
}

# Shorten Table Of Contents in API documentation
object_description_options = [
    (".*", {"include_fields_in_toc": False}),
    (".*parameter", {"include_in_toc": False}),
]

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named 'default.css' will overwrite the builtin 'default.css'.
html_static_path = ["_static"]

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
html_last_updated_fmt = today_fmt

# Output file base name for HTML help builder.
htmlhelp_basename = "pds_doc"


# -- Extension configuration -------------------------------------------------
# Configuration of sphinx.ext.autodoc
# https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html
autodoc_typehints = "signature"


# Configuration of sphinx.ext.napoleon
# https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html
# Support for NumPy and Google style docstrings
napoleon_google_docstring = True
napoleon_numpy_docstring = False
# Allow PEP 526 attributes annotations in classes:
napoleon_attr_annotations = True


# Configuration of sphinx.ext.intersphinx
# https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html
# Only projects these docs actually refer to. Every entry costs an inventory
# download on each build (and, under -W, is a way for a network blip to fail it).
intersphinx_mapping = {
    "python": ("https://docs.python.org/3/", None),
    "muscle3": ("https://muscle3.readthedocs.io/en/latest/", None),
    "imas": ("https://imas-python.readthedocs.io/en/latest/", None),
    "ymmsl": ("https://ymmsl-python.readthedocs.io/en/latest/", None),
}
intersphinx_timeout = 60  # Downloads time out after 1 minute

smartquotes = False


def setup(app):
    app.add_css_file("pds.css")
