globals:
  dd_version: 4.0.0
  machine_description:
    equilibrium: 
      imas:hdf5?path=[PWD_PLACEHOLDER]/run/input/test_data_ids/
    pf_active:
      imas:hdf5?path=[PWD_PLACEHOLDER]/run/input/test_data_ids/
equilibrium:
  equilibrium/time_slice/global_quantities/ip:
  - {type: constant, value: -1.5e7}
pf_active:
  pf_active/coil(1)/current/data:
  - {type: constant, value: 10000}
